import {
  faharicars,
  nobeltradingltd,
  premierbank,
  yahyacarsLogo,
  alsiddiquemotors,
  autoboxmotors,
  magariland,
  nihon,
  ranacars,
  sleekrides,
  thymotors,
  yuasatrading,
  ali,
  kainat,
  mulazai,
  toyopet,
  abdula,
  azan,
  arham,
  hakki,
  eyre,
  skyracer,
  togo,
  classic,
  farhan,
  khilji,
  yanshan
} from "../../../assets/images/ourClients";

export const clients = [
  { id: 1, img: farhan, name: "Farhan", link: "#" },
  { id: 2, img: khilji, name: "Khilji", link: "#" },
  { id: 3, img: yanshan, name: "Yanshan", link: "#" },
  { id: 4, img: hakki, name: "Hakki Co. Ltd", link: "#" },
  { id: 5, img: premierbank, name: "Premier Bank", link: "#" },
  { id: 6, img: faharicars, name: "Fahari Cars", link: "#" },
  { id: 7, img: yahyacarsLogo, name: "Yahya Cars", link: "#" },
  { id: 8, img: classic, name: "Classic", link: "#" },
  { id: 9, img: alsiddiquemotors, name: "Al Siddique Motors", link: "#" },
  { id: 10, img: autoboxmotors, name: "Autobox Motors", link: "#" },
  { id: 11, img: nobeltradingltd, name: "Nobel Trading Ltd", link: "#" },
  { id: 12, img: magariland, name: "Magariland", link: "#" },
  { id: 13, img: abdula, name: "Abdula Motors", link: "#" },
  { id: 14, img: azan, name: "Azan Enterprises", link: "#" },
  { id: 15, img: arham, name: "Arham Traders", link: "#" },
  { id: 16, img: nihon, name: "Nihon", link: "#" },
  { id: 17, img: ranacars, name: "Rana Cars", link: "#" },
  { id: 18, img: sleekrides, name: "Sleekrides Motors", link: "#" },
  { id: 19, img: thymotors, name: "Thy Motors", link: "#" },
  { id: 20, img: yuasatrading, name: "Yuasa Trading", link: "#" },
  { id: 21, img: ali, name: "Ali Enterprises", link: "#" },
  { id: 22, img: kainat, name: "Kainat Traders", link: "#" },
  { id: 23, img: mulazai, name: "Mulazai Corporation", link: "#" },
  { id: 24, img: toyopet, name: "Toyopet Dealers", link: "#" },
  { id: 25, img: eyre, name: "Eyre", link: "#" },
  { id: 26, img: skyracer, name: "SkyRacer", link: "#" },
  { id: 27, img: togo, name: "Togo", link: "#" },
];