import {
  faharicars,
  nobeltradingltd,
  premierbank,
  yahyacarsLogo,
  alsiddiquemotors,
  autoboxmotors,
  bolpaktrading,
  cheematrailers,
  magariland,
  nihon,
  ranacars,
  sammytraders,
  sleekrides,
  thymotors,
  yuasatrading,
  ali,
  kainat,
  mulazai,
  toyopet,
  abdula,
  azan,
  arham,
} from "../../../assets/images/ourClients";


export const clients = [
  { id: 1, img: premierbank, name: "Premier Bank", link: "#" },
  { id: 2, img: faharicars, name: "Fahari Cars", link: "#" },
  { id: 3, img: yahyacarsLogo, name: "Yahya Cars", link: "#" },
  { id: 4, img: alsiddiquemotors, name: "Al Siddique Motors", link: "#" },
  { id: 5, img: autoboxmotors, name: "Autobox Motors", link: "#" },
  { id: 6, img: nobeltradingltd, name: "Nobel Trading Ltd", link: "#" },
  { id: 7, img: bolpaktrading, name: "Bolpak Trading", link: "#" },
  { id: 8, img: cheematrailers, name: "Cheema Trailers", link: "#" },
  { id: 9, img: magariland, name: "Magariland", link: "#" },
  { id: 10, img: nihon, name: "Nihon", link: "#" },
  { id: 11, img: ranacars, name: "Rana Cars", link: "#" },
  { id: 12, img: sammytraders, name: "Sammy Traders", link: "#" },
  { id: 13, img: sleekrides, name: "Sleekrides Motors", link: "#" },
  { id: 14, img: thymotors, name: "Thy Motors", link: "#" },
  { id: 15, img: yuasatrading, name: "Yuasa Trading", link: "#" },
  { id: 16, img: ali, name: "Ali Enterprises", link: "#" },
  { id: 17, img: kainat, name: "Kainat Traders", link: "#" },
  { id: 18, img: mulazai, name: "Mulazai Corporation", link: "#" },
  { id: 19, img: toyopet, name: "Toyopet Dealers", link: "#" },
  { id: 20, img: abdula, name: "Abdula Motors", link: "#" },
  { id: 21, img: azan, name: "Azan Enterprises", link: "#" },
  { id: 22, img: arham, name: "Arham Traders", link: "#" },
];
